# Select image from https://hub.docker.com/_/php
image: php:7.3

# Select what we should cache
cache:
  paths:
  - vendor/

before_script:
  
  # Install dependencies
  - bash ci/docker_install.sh > /dev/null
    
  # Install composer
  - curl -sS https://getcomposer.org/installer | php

  # Install all project dependencies
  - php composer.phar install
    
  - php -d extension=grpc


test:app:
    script:
        - vendor/bin/phpunit --configuration phpunit_myapp.xml

