# Select image from https://hub.docker.com/_/php
image: php:7.3

# Select what we should cache
cache:
  paths:
  - vendor/

before_script:
  - apt-get update -y
  - apt-get upgrade -y
  - apt-get install sudo -y
  - apt-get install zlib1g-dev

  # Install dependencies
  - bash ci/docker_install.sh > /dev/null
    
  # Install composer
  - curl -sS https://getcomposer.org/installer | php

  - php --ini 
  - sudo pecl install grpc
  - sudo docker-php-ext-enable grpc
  
  # Install all project dependencies
  - echo "extension=grpc.so" > /usr/local/etc/php && echo "extension=grpc.so" > /usr/local/etc/php/conf.d/docker-php-ext-sodium.ini && php composer.phar update
    


test:app:
    script:
        - vendor/bin/phpunit --configuration phpunit_myapp.xml

