;[PHP]
;
;;Enable the PHP scripting language
;engine=On
;
;; The root of the PHP pages, used only if nonempty.
;;doc_root="./pages"
;
;;The base name of the directory used on a user's home directory for PHP files, for example public_html .
;;user_dir="./pages"
;
;; Directory in which the loadable extensions (modules) reside.
;extension_dir="./ext"
;
;extension = "grpc"
;
;
;