<?php

/*
 * @author yanying (Tracie)
 */
/* Load Config File */
require_once '../resources/config.php';
require_once TIME_MOD . '/Time.php';
require_once ENUMS_PATH . '/Appointment_Status.php';

require_once DB_MOD . '/DbQuery.php';
require_once DB_MOD . '/Database.php';

require_once APPT_MOD . '/Appointment_Slot.php';
require_once FACILITY_MOD . '/Medical_Facility.php';

class Appointment_Record {

    // Properties
    # Appointment Created on (Date & Time)
    private Time $createdon;
    # Appointment ID Generated By Firestore Or Code Generated?? -- Using Document ID First
    private string $appointmentid;

    # Appointment Status (Upcoming, Missed, etc...) -- Need To Call A Function To Update Status When Directed To The Page or Reload
    private string $appointmentstatus;

    # Appointment Type (e.g. Specialist, Doctor Consultation)
    private string $appointmenttype;

    # Appointment Slot
    private Appointment_Slot $appointmentslot;

    # Appointment Venue (The Location)
    private Medical_Facility $facility;

    // Constructor
    function __construct(Time $createdon, string $appointmentid, string $appointmenttype, Appointment_Slot $appointmentslot,
            Medical_Facility $facility, string $appointmentstatus = Appointment_Status::UPCOMING) {

        $this->createdon = $createdon;
        $this->appointmentslot = $appointmentslot;
        $this->appointmentid = $appointmentid;
        $this->appointmenttype = $appointmenttype;
        $this->appointmentstatus = $appointmentstatus;
        $this->facility = $facility; // -- Medical_Facility Object -- //
    }

    // Getters
    public function get_appointmentid(): string {
        return $this->appointmentid;
    }

    public function get_appointmenttype(): string {
        return $this->appointmenttype;
    }

    public function get_appointmentstatus(): string {
        return $this->appointmentstatus;
    }

    public function get_appointmentslot(): Appointment_Slot {
        return $this->appointmentslot;
    }

    public function get_facility(): Medical_Facility {
        return $this->facility;
    }

    // Setters
    public function set_appointmentid(string $appointmentid): void {
        $this->appointmentid = $appointmentid;
    }

    public function set_appointmentstatus(string $appointmentstatus): void {
        $this->appointmentstatus = $appointmentstatus;
    }

    public function set_appointmenttype(string $appointmenttype): void {
        $this->appointmenttype = $appointmenttype;
    }

    public function set_appointmentslot(Appointment_Slot $appointmentslot): void {
        $this->appointmentslot = $appointmentslot;
    }

    public function set_facility(Medical_Facility $facility): void {
        $this->facility = $facility;
    }

    // Use For Debugging/ Logging Purpose
    public function __toString(): string {
        $str = nl2br(PHP_EOL . "Created On: " . $this->createdon . PHP_EOL . 'Appointment ID: ' . $this->appointmentid .
                PHP_EOL . 'Appointment Status ' . $this->appointmentstatus .
                PHP_EOL . 'Scheduled On: ' . $this->scheduledon . PHP_EOL
                . 'Location ' . $this->facility);
        return $str;
    }

    // -- Initialise Appointment_Records
    public static function initialise_appointment_record(array $appt_record): Appointment_Record {

        # Time (Createdon)
        $createdon = new Time($appt_record['createdon']['date'], $appt_record['createdon']['time']);

        # Appointment Slot
        $appt_slot = Appointment_Slot::retrieve_apptslot_by_id($appt_record['slotid'], $appt_record['appointmenttype']);

        # Medical Facility
        $facility = Medical_Facility::retrieve_facility_by_id($appt_record['facilityid']);
        $appt_record_obj = new Appointment_Record($createdon, $appt_record['appointmentid'], $appt_record['appointmenttype'],
                $appt_slot, $facility, $appt_record['appointmentstatus']);

        # -- Return 
        return $appt_record_obj;
    }

    // ####################     Database Functions      ################### //
    // -- BOOK AN APPOINTMENT
    public static function book_appointment(string $email, array $booking_info): bool {

        $condition['credentials'] = array('email' => $email);
        $db = new DbQuery();
        $user_doc_id = $db->get_document_id(Database::ACCOUNT_USER, $condition);

        # Validate Appointment
        if (self::validate_appt_booking($user_doc_id, $booking_info)):

            # Create User Appointment Record
            $user_appt_update = self::create_appointment_record($db, $user_doc_id, $booking_info);

            # If User Appointment Record Created Successfully
            if ($user_appt_update):

                # Update To Add Patient's ID To Appointment's patient array
                $appt_slot_update = self::add_patient_to_slot($db, $user_doc_id, $booking_info);
                return ($user_appt_update && $appt_slot_update);
            else:
                return false;
            endif;

        endif;
        return false;
    }

    // -- CREATE APPOINTMENT RECORD
    private static function create_appointment_record(DbQuery $db, string $user_doc_id, array $booking_info): bool {

        # SET Appointment Booking Information
        $appointment_info['appointmenttype'] = $booking_info['appointmenttype'];
        $appointment_info['facilityid'] = $booking_info['facilityid'];
        $appointment_info['scheduledon'] = array(
            'date' => $booking_info['date'],
            'time' => $booking_info['time']
        );

        # SET Appointment Creation Time
        $createdon = new Time();
        $appointment_info['createdon'] = array(
            'date' => $createdon->get_date(),
            'time' => $createdon->get_time()
        );

        # SET Default Appointment Status
        $appointment_info['appointmentstatus'] = Appointment_Status::UPCOMING;

        # Get Appointment ID
        $id = self::generate_appointment_id($user_doc_id);
        $appointment_info['appointmentid'] = $id;

        # Add The AppointmentRecord To The Database
        $appt_doc_path = Database::ACCOUNT_USER . "/" . $user_doc_id . "/" . Database::APPOINTMENT_RECORD;
        return $db->insert_data($appt_doc_path, $appointment_info, false, $id);
    }

    // -- UPDATE APPOINTMENT SLOT
    private static function add_patient_to_slot(DbQuery $db, string $user_doc_id, array $booking_info): bool {

        # Update The Appointment Slot (Not Done)
        $user_id_arr['patients'] = array($user_doc_id);
        $slots_doc_path = Database::MEDICAL_FACILITY . "/" . $booking_info['facilityid'] . "/" .
                $booking_info['appointmenttype'] . "/" . $booking_info['date'] . "/" . Database::SLOTS;
        return $db->update_array_add($slots_doc_path, $booking_info['slotid'], $user_id_arr);
    }

    // -- Validate Appointment Booking -- //
    private static function validate_appt_booking(string $user_doc_id, array $booking_info): bool {

        # Declaring The Conditions
        $conditions = array(
            'appointmentstatus' => Appointment_Status::UPCOMING,
            'appointmenttype' => $booking_info['appointmenttype'],
            'facilityid' => $booking_info['facilityid'],
            'scheduledon' => array(
                'date' => $booking_info['date'],
                'time' => $booking_info['time']
            )
        );

        # Search For Same Appointment
        $db = new DbQuery();
        $path = Database::ACCOUNT_USER . "/" . $user_doc_id . "/" . Database::APPOINTMENT_RECORD;
        $same_appt = $db->select_exact_match($path, $conditions);
        return $validate_status = ($same_appt == null) ? true : false;
    }

    // -- User-Defined ID -- //
    private static function generate_appointment_id(string $user_doc_id) {

        # To OrderBy The Appointment ID
        $orderBy = array('appointmentid');

        # Find The Last ID & Increment
        $db = new DbQuery();
        $doc_path = Database::ACCOUNT_USER . "/" . $user_doc_id . "/" . Database::APPOINTMENT_RECORD;
        $last_id_appointment = $db->get_documentid_ordered($doc_path, $orderBy, false);

        echo "The last id:" . $last_id_appointment;
        # If There Is Any Present ID In Database
        $current_year = Time::get_current_year();
        if ($last_id_appointment != null) :

            $last_id = explode("-", $last_id_appointment);
            $last_id_date = $last_id[1];

            # Compare Year
            if ($last_id_date == $current_year):

                # Increase The Number
                $new_id = ++$last_id[2];
                echo "Same Year";
                return $last_id[0] . "-" . $last_id[1] . "-" . $new_id;
            else:
                echo "A New Year";
                return $last_id[0] . "-" . $current_year . "-1000";

            endif;

        # No ID Present In Database
        else:
            return "appt-" . $current_year . "-1000";
        endif;
    }

    // -- Retrieve Of Appointment Records Of Certain Type -- //
    private static function retrieve_patient_appointment(array $email, ?array $appointmentstatus = NULL): array {

        # Array Of Appointments
        $appointment_arr = array();

        # Query For Upcoming Appointment Records
        $db = new DbQuery();

        $doc_id = $db->get_document_id(Database::ACCOUNT_USER, $email);
        $doc_path = Database::ACCOUNT_USER . "/" . $doc_id . "/" . Database::APPOINTMENT_RECORD;

        # Check If Need To Filter By Appointment Status
        if ($appointmentstatus == NULL):
            $record_list = $db->get_documents_by_path($doc_path, False);
        else:
            $record_list = $db->get_documents_by_path($doc_path, True, $appointmentstatus);
        endif;

        # Create Appointment Record Object List
        foreach ($record_list as $record) :

            $appointment_arr[] = self::initialise_appointment_record($record);

        endforeach;
        return $appointment_arr;
    }

    // -- GET ALL APPOINTMENT RECORDS
    public static function retrieve_patient_all_appointments(array $email): array {
        return self::retrieve_patient_appointment($email);
    }

    // -- FILTER APPOINTMENTS TO APPOINTMENT STATUS -- //
    public static function sort_appointment_by_status(array $appt_arr): array {

        # Create Empty Container
        $arr ['upcoming'] = array();
        $arr['missed'] = array();
        foreach ($appt_arr as $appt):

            # FILTER
            if ($appt->get_appointmentstatus() == Appointment_Status::UPCOMING):
                $arr['upcoming'][] = $appt;
            elseif ($appt->get_appointmentstatus() == Appointment_Status::MISSED):
                $arr['cancelled'][] = $appt;
            endif;
        endforeach;
        return $arr;
    }

    // -- GET UPCOMING APPOINTMENT RECORDS
    public static function retrieve_upcoming_appointments(array $email): array {

        # Set Default Appointment Status
        $appointmentstatus['appointmentstatus'] = Appointment_Status::UPCOMING;

        # Retrieving List Of Upcoming Appointments
        $upcoming_arr = self::retrieve_patient_appointment($email, $appointmentstatus);

        return $upcoming_arr;
    }

    // -- GET MISSED APPOINTMENT RECORDS  [last 14 days]
    public static function retrieve_missed_appointments(array $email): array {

        # Set Default Appointment Status
        $appointmentstatus['appointmentstatus'] = Appointment_Status::MISSED;

        # Retrieving List Of Missed Appointments
        $missed_arr = self::retrieve_patient_appointment($email, $appointmentstatus);

        return $missed_arr;
    }

    // -- RESCHEDULE APPOINTMENT
    public static function reschedule_appointment(string $email, string $appointmentid, array $scheduledon) {

        # Conditions (For Outer Collection)
        $condition['credentials'] = array('email' => $email);

        # Sub-Conditions (For Inner Collection)
        $subcondition = array('appointmentid' => $appointmentid);

        # RESET Default Appointment Status (To Cater To MISSED Appointments)
        $changed_info['appointmentstatus'] = Appointment_Status::UPCOMING;

        # Add The Rescheduled Time To Array
        $changed_info['scheduledon'] = $scheduledon;

        # Update The Modified Information
        $db = new DbQuery();
        return $db->modify_nested_collection(Database::ACCOUNT_USER, Database::APPOINTMENT_RECORD,
                        $condition, $subcondition, $changed_info);
    }

    // -- CANCEL APPOINTMENT
    public static function cancel_appointment(string $email, string $appointmentid): bool {

        # Conditions (For Outer Collection)
        $condition['credentials'] = array('email' => $email);

        # Get User Document ID
        $db = new DbQuery();
        $user_doc_id = $db->get_document_id(Database::ACCOUNT_USER, $condition);

        # SET Appointment Status To Cancelled After Patient Cancel Appointment
        $changed_info['appointmentstatus'] = Appointment_Status::CANCELLED;

        # Update The Patient's Appointment Record
        $user_appt_path = Database::ACCOUNT_USER . "/" . $user_doc_id . "/" . Database::APPOINTMENT_RECORD;
        $user_appt_update = $db->update_document_by_path($user_appt_path, $appointmentid, $changed_info);


        if ($user_appt_update):
            # Get Appointment Record In Array
            $appt_record = $db->get_document($user_appt_path, $appointmentid);

            # Update The Appointment Slot
            $appt_slot_update = self::remove_patient_from_slot($db, $user_doc_id, $appt_record);

            return ($user_appt_update && $appt_slot_update);
        endif;
        return false;
    }

    // -- REMOVE PATIENT FROM SLOT WHEN CANCELLING APPOINTMENT
    private static function remove_patient_from_slot(DbQuery $db, $user_doc_id, array $appt_record): bool {

        # Appointment Schedule
        $scheduledon = $appt_record['scheduledon'];

        # Patient Document ID In Array (To Be Removed)
        $user_id_arr['patients'] = array($user_doc_id);

        # Get Appointment Slot's ID
        $slot_path = Database::MEDICAL_FACILITY . "/" . $appt_record['facilityid'] . "/" . $appt_record['appointmenttype'] . "/" . $scheduledon['date'] . "/" . Database::SLOTS;
        $slot_condition = array('time' => $scheduledon['time']);
        $slot_doc_id = $db->get_document_id($slot_path, $slot_condition);


        return $db->update_array_remove($slot_path, $slot_doc_id, $user_id_arr);
    }

    // -- RETRIEVE APPOINTMENT BY APPOINTMENT ID
    public static function retrieve_appointment_by_id(string $user_email, string $appointmentid): array {
        $condition['credentials'] = array('email' => $user_email);
        $db = new DbQuery();
        $user_doc_id = $db->get_document_id(Database::ACCOUNT_USER, $condition);

        # Query For The Particular Appointment Slot
        $doc_path = Database::ACCOUNT_USER . "/" . $user_doc_id . "/" . Database::APPOINTMENT_RECORD;
        $appt_record = $db->get_document($doc_path, $appointmentid);

        $appt_record_obj = self::initialise_appointment_record($appt_record);

        return $appt_record_obj;
    }

}

?>
