<?php

/*
 * @author yanying (Tracie)
 */
/* Load Config File */
//require_once '../resources/config.php';
require_once TIME_MOD . '/Time.php';
require_once ENUMS_PATH . '/Appointment_Status.php';

require_once DB_MOD . '/DbQuery.php';
require_once DB_MOD . '/Database.php';

require_once APPT_MOD . '/Appointment_Slot.php';
require_once APPT_MOD . '/Special_Slot.php';
require_once APPT_MOD . '/Normal_Slot.php';
require_once FACILITY_MOD . '/Medical_Facility.php';

use Google\Cloud\Firestore\Transaction;

class Appointment_Record {

    // Properties
    # Appointment Created on (Date & Time)
    private Time $createdon;
    # Appointment ID Generated By Firestore Or Code Generated?? -- Using Document ID First
    private string $appointmentid;

    # Appointment Status (Upcoming, Missed, etc...) -- Need To Call A Function To Update Status When Directed To The Page or Reload
    private string $appointmentstatus;

    # Appointment Type (e.g. Specialist, Doctor Consultation)
    private string $appointmenttype;

    # Appointment Slot
    private Appointment_Slot $appointmentslot;

    # Appointment Venue (The Location)
    private Medical_Facility $facility;

    # Medical Record ID
    private string $mrid;

    // Constructor
    function __construct(Time $createdon, string $appointmentid, string $appointmenttype, Appointment_Slot $appointmentslot,
            Medical_Facility $facility, string $appointmentstatus = Appointment_Status::UPCOMING, string $mrid = "") {

        $this->createdon = $createdon;
        $this->appointmentslot = $appointmentslot;
        $this->appointmentid = $appointmentid;
        $this->appointmenttype = $appointmenttype;
        $this->appointmentstatus = $appointmentstatus;
        $this->facility = $facility; // -- Medical_Facility Object -- //
        $this->mrid = $mrid;
    }

    // Getters
    public function get_appointmentid(): string {
        return $this->appointmentid;
    }

    public function get_appointmenttype(): string {
        return $this->appointmenttype;
    }

    public function get_appointmentstatus(): string {
        return $this->appointmentstatus;
    }

    public function get_appointmentslot(): Appointment_Slot {
        return $this->appointmentslot;
    }

    public function get_facility(): Medical_Facility {
        return $this->facility;
    }

    // Setters
    public function set_appointmentid(string $appointmentid): void {
        $this->appointmentid = $appointmentid;
    }

    public function set_appointmentstatus(string $appointmentstatus): void {
        $this->appointmentstatus = $appointmentstatus;
    }

    public function set_appointmenttype(string $appointmenttype): void {
        $this->appointmenttype = $appointmenttype;
    }

    public function set_appointmentslot(Appointment_Slot $appointmentslot): void {
        $this->appointmentslot = $appointmentslot;
    }

    public function set_facility(Medical_Facility $facility): void {
        $this->facility = $facility;
    }

    // Use For Debugging/ Logging Purpose
    public function __toString(): string {
        $str = nl2br(PHP_EOL . "Created On: " . $this->createdon . PHP_EOL . 'Appointment ID: ' . $this->appointmentid .
                PHP_EOL . 'Appointment Status ' . $this->appointmentstatus .
                PHP_EOL . 'Scheduled On: ' . $this->scheduledon . PHP_EOL
                . 'Location ' . $this->facility);
        return $str;
    }

    // -- Initialise Appointment_Records
    public static function initialise_appointment_record(array $appt_record): ?Appointment_Record {
        try {
            # Time (Createdon)
            $createdon = new Time($appt_record['createdon']['date'], $appt_record['createdon']['time']);

            # Appointment Slot
            $appt_slot = self::retrieve_slot($appt_record['slotid'], $appt_record['appointmenttype'], $appt_record['facilityid']);

            # Medical Facility
            $facility = Medical_Facility::retrieve_facility_by_id($appt_record['facilityid']);
            $appt_record_obj = new Appointment_Record($createdon, $appt_record['appointmentid'], $appt_record['appointmenttype'],
                    $appt_slot, $facility, $appt_record['appointmentstatus'], $appt_record['mrid']);

            # -- Return 
            return $appt_record_obj;
        } catch (Exception $e) {
            return null;
        }
    }

    // ####################     Database Functions      ################### //
    // -- CREATE APPOINTMENT RECORD
    public static function create_appointment_record(string $user_doc_id, array $booking_info): ?Appointment_Record {

        $db = new DbQuery();

        # SET Appointment Creation Time
        $createdon = new Time();

        # Get Appointment ID
        $id = self::generate_appointment_id($user_doc_id);

        # Add The AppointmentRecord As Sub Collection Nested In Patient Database
        $appt_doc_path = Database::ACCOUNT_USER . "/" . $user_doc_id . "/" . Database::APPOINTMENT_RECORD;
        $batch = $db->get_db()->batch();

        $appt_record_arr = array(
            'appointmentid' => $id,
            'appointmenttype' => $booking_info['appointmenttype'],
            'appointmentstatus' => Appointment_Status::UPCOMING,
            'facilityid' => $booking_info['facilityid'],
            'createdon' => ['date' => $createdon->get_date(), 'time' => $createdon->get_time()],
            'slotid' => $booking_info['slotid'],
            'mrid' => ''
        );

        $batch->set($db->get_db()->collection($appt_doc_path)->document($id), $appt_record_arr);
        $batch->commit();

        return self::initialise_appointment_record($appt_record_arr);
    }

    public static function set_mrid(string $patientid, string $slotid, string $mrid): bool {
        $db = new DbQuery();
        $doc_path = Database::ACCOUNT_USER . "/" . $patientid . "/" . Database::APPOINTMENT_RECORD;
        $documents = $db->get_db()->collection($doc_path)->where('slotid', "=", $slotid)->where("mrid", "!=", "")->documents();
        foreach ($documents as $doc):
            if ($doc->exists()):
                $appt_id = $doc->id(); // Finding The Appt ID
                break;
            endif;
        endforeach;

        // Use The Appt ID & Set The mrid 
        if ($appt_id !== null):
            $doc_ref = $db->get_db()->collection($doc_path)->document($appt_id);
            $trxn_result = $db->get_db()->runTransaction(function (Transaction $transaction) use ($doc_ref, $mrid) {
                $snapshot = $transaction->snapshot($doc_ref);
                $db_mrid = $snapshot['mrid'];
                if ($db_mrid == ""):
                    $transaction->update($doc_ref, [['path', 'mrid', 'value', $mrid]]);
                    return true;
                endif;
                return false;
            });
            return $trxn_result;
        endif;
        return false;
    }

    // -- Validate Appointment Booking  (Check If Patient Have Same Appointment) -- //
    public static function validate_appt_booking(string $user_doc_id, array $booking_info): null|bool {

        # Search For Same Appointment
        if ($booking_info['slotid'] !== null || !empty($booking_info['slotid'])):
            $booking_date = explode("~", $booking_info['slotid'])[1];
            $db = new DbQuery();
            $path = Database::ACCOUNT_USER . "/" . $user_doc_id . "/" . Database::APPOINTMENT_RECORD;
            $snapshot = $db->get_db()->collection($path)
                            ->where("appointmentstatus", "=", Appointment_Status::UPCOMING)
                            ->where("appointmenttype", "=", $booking_info['appointmenttype'])->documents();

            # Loop & Check If There Is Any Match
            foreach ($snapshot as $doc):
                if ($doc->exists()):
                    $comparison_date = explode("~", $doc->data()['slotid'])[1];
                    # Check If Have Same Appointment Type In The Same Day
                    if ($comparison_date == $booking_date):
                        return False;
                    endif;

                endif;

            endforeach;
            return True;
        endif;
        return null;
    }

    // -- User-Defined ID -- //
    private static function generate_appointment_id(string $user_doc_id) {

        # To OrderBy The Appointment ID
        $orderBy = array('appointmentid');

        # Find The Last ID & Increment
        $db = new DbQuery();
        $doc_path = Database::ACCOUNT_USER . "/" . $user_doc_id . "/" . Database::APPOINTMENT_RECORD;
        $last_id_appointment = $db->get_first_id_ordered($doc_path, $orderBy, false);

        # If There Is Any Present ID In Database
        $current_year = Time::get_current_year();
        if ($last_id_appointment != null) :

            $last_id = explode("-", $last_id_appointment);

            # Compare Year
            if ($last_id[1] == $current_year):

                # Increase The Number
                $new_id = ++$last_id[2];

                return $last_id[0] . "-" . $last_id[1] . "-" . $new_id; # -- There is A Current Year Id
            endif;

            return $last_id[0] . "-" . $current_year . "-1000"; # -- There Is No Current Year Id

        endif;
        return "appt-" . $current_year . "-1000"; # -- Totally No ID Present In Database
    }

    // -- Retrieve Of Appointment Records Of Certain Type -- //
    private static function retrieve_patient_appointment(array $email, ?array $appointmentstatus = NULL): array {

        # Array Of Appointments
        $appointment_arr = array();

        # Query For Upcoming Appointment Records
        $db = new DbQuery();

        $doc_id = $db->get_document_id(Database::ACCOUNT_USER, $email);
        $doc_path = Database::ACCOUNT_USER . "/" . $doc_id . "/" . Database::APPOINTMENT_RECORD;

        # Check If Need To Filter By Appointment Status
        if ($appointmentstatus == NULL):
            $record_list = $db->get_documents_by_path($doc_path, False);
        else:
            $record_list = $db->get_documents_by_path($doc_path, True, $appointmentstatus);
        endif;

        # Create Appointment Record Object List
        foreach ($record_list as $record) :

            $appointment_arr[] = self::initialise_appointment_record($record);

        endforeach;
        usort($appointment_arr, array("Appointment_Record", "cmp_obj"));

        return $appointment_arr;
    }

    // -- GET ALL APPOINTMENT RECORDS
    public static function retrieve_patient_all_appointments(array $email): array {
        return self::retrieve_patient_appointment($email);
    }

    // -- FILTER APPOINTMENTS TO APPOINTMENT STATUS -- //
    public static function sort_appointment_by_status(array $appt_arr): array {

        # Create Empty Container
        $arr ['upcoming'] = array();
        $arr['missed'] = array();
        foreach ($appt_arr as $appt):

            # FILTER
            if ($appt->get_appointmentstatus() == Appointment_Status::UPCOMING):
                $arr['upcoming'][] = $appt;
            elseif ($appt->get_appointmentstatus() == Appointment_Status::MISSED):
                $arr['missed'][] = $appt;
            endif;
        endforeach;
//        usort($arr['upcoming'], array("Appointment_Record", "cmp_obj"));
//        usort($arr['missed'], array("Appointment_Record", "cmp_obj"));

        return $arr;
    }

    // -- GET UPCOMING APPOINTMENT RECORDS
    public static function retrieve_upcoming_appointments(array $email): array {

        # Set Default Appointment Status
        $appointmentstatus['appointmentstatus'] = Appointment_Status::UPCOMING;

        # Retrieving List Of Upcoming Appointments
        $upcoming_arr = self::retrieve_patient_appointment($email, $appointmentstatus);

        return $upcoming_arr;
    }

    // -- GET MISSED APPOINTMENT RECORDS  [last 14 days]
    public static function retrieve_missed_appointments(array $email): array {

        # Set Default Appointment Status
        $appointmentstatus['appointmentstatus'] = Appointment_Status::MISSED;

        # Retrieving List Of Missed Appointments
        $missed_arr = self::retrieve_patient_appointment($email, $appointmentstatus);

        return $missed_arr;
    }

    //  ___ For Reschedule Of Appointment ___ // 
    public static function update_appointment_schedule(string $patient_doc_id, string $appointmentid, string $slotid): bool {

        // Appointment Record Path
        $path = Database::ACCOUNT_USER . "/" . $patient_doc_id . "/" . Database::APPOINTMENT_RECORD;

        if ($appointmentid !== null):

            $db = new DbQuery();
            $doc_ref = $db->get_db()->collection($path)->document($appointmentid);

            # Update Appointment Slot ID
            $trnx_result = $db->get_db()->runTransaction(function (Transaction $transaction) use ($doc_ref, $slotid) {
                $snapshot = $transaction->snapshot($doc_ref);
                $db_slotid = $snapshot['slotid'];
                if ($db_slotid !== $slotid):
                    $transaction->update($doc_ref, [
                        ['path' => 'slotid', 'value' => $slotid],
                        ['path' => 'appointmentstatus', 'value' => Appointment_Status::UPCOMING]
                    ]);
                    return true;
                endif;
                return false;
            });
        endif;

        return $trnx_result;
    }

    // -- REMOVE APPOINTMENT RECORD
    public static function remove_appointment_record(string $patient_doc_id, string $appointmentid): Appointment_Record {

        $db = new DbQuery();

        # Update The Patient's Appointment Record (DELETE APPOINTMENT RECORD)
        $user_appt_path = Database::ACCOUNT_USER . "/" . $patient_doc_id . "/" . Database::APPOINTMENT_RECORD;

        # Get Appt Details (slotid)
        $appt = $db->get_db()->collection($user_appt_path)->document($appointmentid);

        if ($appt->snapshot()->exists()):

            # Retrieving The Data Before Deletion
            $appt_details = $appt->snapshot()->data();

            # Appointment Record Object
            $appt_obj = self::initialise_appointment_record($appt_details);

            # Delete The Appointment Record
            $appt->delete();

            return $appt_obj;
        endif;
    }

    // -- REMOVE PATIENT FROM SLOT
    public static function remove_patient_from_slot(string $slotid, string $appointmenttype, string $patient_doc_id) {

        switch ($appointmenttype):
            case Appointment_Type::CHECK_UP:
            case Appointment_Type::DOCTOR_CONSULTATION:
                Normal_Slot::remove_patient_from_slot($slotid, $patient_doc_id);
                break;
            case Appointment_Type::SPECIALIST_CONSULTATION:
                Special_Slot::remove_patient_from_slot($slotid);
                break;
        endswitch;
    }

    // -- RETRIEVE APPOINTMENT SLOTS BY ID 
    public static function retrieve_slot(string $slotid, string $appointmenttype, string $facilityid): Appointment_Slot {

        # Slots Container
        $slots_arr = array();

        switch ($appointmenttype):
            case Appointment_Type::CHECK_UP:
            case Appointment_Type::DOCTOR_CONSULTATION:
                $slots_arr = Normal_Slot::retrieve_apptslot_by_id($slotid, $facilityid);
                break;
            case Appointment_Type::SPECIALIST_CONSULTATION:
                $slots_arr = Special_Slot::retrieve_apptslot_by_id($slotid, $facilityid);
                break;
        endswitch;

        return $slots_arr;
    }

    // -- RETRIEVE APPOINTMENT BY APPOINTMENT ID
    public static function retrieve_appointment_by_id(string $user_email, string $appointmentid): null|Appointment_Record {
        $condition['credentials'] = array('email' => $user_email);
        $db = new DbQuery();
        $user_doc_id = $db->get_document_id(Database::ACCOUNT_USER, $condition);

        # Query For The Particular Appointment Slot
        $doc_path = Database::ACCOUNT_USER . "/" . $user_doc_id . "/" . Database::APPOINTMENT_RECORD;

        $appt_record = $db->fetch_document_by_id($doc_path, $appointmentid);

        if ($appt_record !== null):
            $appt_record_obj = self::initialise_appointment_record($appt_record);
            return $appt_record_obj;
        endif;
        return null;
    }

    // -- Comparison Function 
    protected static function cmp_obj(Appointment_Record $a, Appointment_Record $b) {
        $format = Time::DATE_FORMAT_DEFAULT . ' ' . Time::TIME_FORMAT_DEFAULT_NOSECONDS;
        $al = DateTime::createFromFormat($format,
                        $a->get_appointmentslot()->get_appointmentschedule()->get_date() . ' ' .
                        $a->get_appointmentslot()->get_appointmentschedule()->get_time());
        $bl = DateTime::createFromFormat($format,
                        $b->get_appointmentslot()->get_appointmentschedule()->get_date() . ' ' .
                        $b->get_appointmentslot()->get_appointmentschedule()->get_time());

        if ($al == $bl) {
            return 0;
        }
        return ($al > $bl) ? +1 : -1;
    }

    public static function retrieve_appointmenttype(string $patientid, string $slotid): ?string {
        $db = new DbQuery();
        $doc_path = Database::ACCOUNT_USER . "/" . $patientid . "/" . Database::APPOINTMENT_RECORD;
        $documents = $db->get_db()->collection($doc_path)->where('slotid', "=", $slotid)->documents();

        foreach ($documents as $doc):
            if ($doc->exists()):
                return $doc->data()['appointmenttype'];
            endif;
        endforeach;
        return null;
    }

    public static function check_mrid_exist(string $patientid, string $slotid): bool|string {

        $db = new DbQuery();
        $doc_path = Database::ACCOUNT_USER . "/" . $patientid . "/" . Database::APPOINTMENT_RECORD;
        $documents = $db->get_db()->collection($doc_path)
                ->where('slotid', "=", $slotid)
                ->where("mrid", "!=", "")
                ->documents();

        foreach ($documents as $doc):
            if ($doc->exists()):
                return $doc->data()['mrid'];
            endif;
        endforeach;
        return false;
    }

}

?>
