<?php

/*
 * @author yanying (Tracie)
 */
/* Load Config File */
require_once '../resources/config.php';
require_once 'Time.php';
require_once ENUMS_PATH . '/Appointment_Status.php';
require_once ENTITIES_PATH . '/Medical_Facility.php';

require_once UTILS_PATH . '/DbQuery.php';
require_once UTILS_PATH . '/Database.php';

class Appointment_Record {

    // Properties
    # Appointment Created on (Date & Time)
    private Time $createdon;
    # Appointment ID Generated By Firestore Or Code Generated?? -- Using Document ID First
    private string $appointmentid;

    # Appointment Status (Upcoming, Missed, etc...) -- Need To Call A Function To Update Status When Directed To The Page or Reload
    private string $appointmentstatus;

    # Appointment Type (e.g. Specialist, Doctor Consultation)
    private string $appointmenttype;

    # Appointment Slot
    private Appointment_Slot $appointmentslot;

    # Appointment Venue (The Location)
    private Medical_Facility $facility;

    // Constructor
    function __construct(Time $createdon, string $appointmentid, string $appointmenttype, Appointment_Slot $appointmentslot,
            Medical_Facility $facility, string $appointmentstatus = Appointment_Status::UPCOMING) {

        $this->createdon = $createdon;
        $this->appointmentslot = $appointmentslot;
        $this->appointmentid = $appointmentid;
        $this->appointmenttype = $appointmenttype;
        $this->appointmentstatus = $appointmentstatus;
        $this->facility = $facility; // -- Medical_Facility Object -- //
    }

    // Getters
    public function get_appointmentid(): string {
        return $this->appointmentid;
    }

    public function get_appointmenttype(): string {
        return $this->appointmenttype;
    }

    public function get_appointmentstatus(): string {
        return $this->appointmentstatus;
    }

    public function get_appointmentslot(): Appointment_Slot {
        return $this->appointmentslot;
    }

    public function get_facility(): Medical_Facility {
        return $this->facility;
    }

    // Setters
    public function set_appointmentid(string $appointmentid): void {
        $this->appointmentid = $appointmentid;
    }

    public function set_appointmentstatus(string $appointmentstatus): void {
        $this->appointmentstatus = $appointmentstatus;
    }

    public function set_appointmenttype(string $appointmenttype): void {
        $this->appointmenttype = $appointmenttype;
    }

    public function set_appointmentslot(Appointment_Slot $appointmentslot): void {
        $this->appointmentslot = $appointmentslot;
    }

    public function set_facility(Medical_Facility $facility): void {
        $this->facility = $facility;
    }

    // Use For Debugging/ Logging Purpose
    public function __toString(): string {
        $str = nl2br(PHP_EOL . "Created On: " . $this->createdon . PHP_EOL . 'Appointment ID: ' . $this->appointmentid .
                PHP_EOL . 'Appointment Status ' . $this->appointmentstatus .
                PHP_EOL . 'Scheduled On: ' . $this->scheduledon . PHP_EOL
                . 'Location ' . $this->facility);
        return $str;
    }

    // -- Set Appointment Reminder -- //
}

?>
