<!-- 
    Developed By FYP-21-S2-24
-->

<?php
/*
 * @author yanying (Tracy)
 */
/* Load Config File */
require_once '../resources/config.php';
require_once ENUMS_PATH . '/Appointment_Status.php';

class Appointment_Record {

    // Properties
    # Appointment ID Generated By Firestore Or Code Generated??
    private string $appointmentid;

    # Appointment Status (Upcoming, Missed, Open, etc...) -- Need To Call A Function To Update Status When Directed To The Page or Reload
    private string $appointmentstatus;

    # Appointment Date [e.g. 01-01-2021]
    private string $date;

    # Appointment Time
    private string $time;

    # Appointment Venue
    private string $location;

    protected const APPOINTMENT_RECORD = "Appointment_Record";

    // Constructor
    function __construct($date, $time, $location) {
        $this->appointmentstatus = Appointment_Status::UPCOMING;
        $this->date = $date;
        $this->time = $time;
        $this->location = $location;
    }

    // Getters
    public function get_appointmentid() {
        return $this->appointmentid;
    }

    public function get_date() {
        return $this->date;
    }

    public function get_time() {
        return $this->time;
    }

    public function get_location() {
        return $this - location;
    }

    // Setters
    public function set_date(string $date) {
        $this->date = $date;
    }

    public function set_time(string $time) {
        $this->time = $time;
    }

    // Use For Debugging/ Logging Purpose
    public function __toString(): string {
        $str = nl2br('Appointment ID: ' . $this->appointmentid . PHP_EOL . 'Appointment Status ' . $this->appointmentstatus . PHP_EOL . 'Date: ' . $this->date .
                PHP_EOL . 'Time: ' . $this->time . PHP_EOL . 'Location ' . $this->location);
        return $str;
    }

    //============================================
    //      Methods Accessing Firestore Database 
    //============================================
    // Create Appointment
    public static function create_appointment(array $appointment_info) {
        $db = new Database();
        $db->insert_data(self::APPOINTMENT_RECORD, $appointment_info);
    }

    // Get Apppointment Record By User??
    public static function get_appointment_record() {
        
    }

}
?>
