<?php

/*
 * @author yanying (Tracy)
 */
/* Load Config File */
require_once '../resources/config.php';
require_once ENUMS_PATH . '/Appointment_Status.php';
require_once ENTITIES_PATH . '/Medical_Facility.php';
require_once UTILS_PATH . '/Time.php';
require_once UTILS_PATH . '/DbQuery.php';
require_once UTILS_PATH . '/Database.php';

class Appointment_Record {

    // Properties
    # Appointment ID Generated By Firestore Or Code Generated?? -- Using Document ID First
    private string $appointmentid;

    # Appointment Status (Upcoming, Missed, etc...) -- Need To Call A Function To Update Status When Directed To The Page or Reload
    private string $appointmentstatus;

    # Appointment Type (e.g. Specialist, Doctor Consultation)
    private string $appointmenttype;

    # Appointment Date & Time [e.g. 01-01-2021]
    private Time $scheduledon;

    # Appointment Venue (The Location)
    private Medical_Facility $facility;

    # Appointment Created on (Date & Time)
    private Time $createdon;

    protected const APPOINTMENT_RECORD = "Appointment_Record";

    // Constructor
    function __construct(Time $createdon, Time $scheduledon, string $appointmentid, string $appointmenttype,
            Medical_Facility $facility, string $appointmentstatus) {
        $this->createdon = $createdon;
        $this->scheduledon = $scheduledon;
        $this->appointmentid = $appointmentid;
        $this->appointmenttype = $appointmenttype;
        if ($appointmentstatus == null) {
            $this->appointmentstatus = Appointment_Status::UPCOMING;
        } else {
            $this->appointmentstatus = $appointmentstatus;
        }
        $this->facility = $facility; // -- Medical_Facility Object -- //
    }

    // Getters
    public function get_appointmentid(): string {
        return $this->appointmentid;
    }

    public function get_appointmenttype(): string {
        return $this->appointmenttype;
    }

    public function get_appointmentstatus(): string {
        return $this->appointmentstatus;
    }

    public function get_scheduledon(): Time {
        return $this->scheduledon;
    }

    public function get_facility(): Medical_Facility {
        return $this->facility;
    }

    // Setters
    public function set_appointmentstatus(string $appointmentstatus): void {
        $this->appointmentstatus = $appointmentstatus;
    }

    public function set_appointmenttype(string $appointmenttype): void {
        $this->appointmenttype = $appointmenttype;
    }

    public function set_date(string $date): void {
        $this->date = $date;
    }

    public function set_time(string $time): void {
        $this->time = $time;
    }

    // Use For Debugging/ Logging Purpose
    public function __toString(): string {
        $str = nl2br(PHP_EOL . "Created On: " . $this->createdon . PHP_EOL . 'Appointment ID: ' . $this->appointmentid .
                PHP_EOL . 'Appointment Status ' . $this->appointmentstatus .
                PHP_EOL . 'Scheduled On: ' . $this->scheduledon . PHP_EOL
                . 'Location ' . $this->facility);
        return $str;
    }

    // -- Set Appointment Reminder -- //
}

?>
