<?php

/*
 * @author yanying (Tracie)
 */

/* Load Config File */
//require_once '../resources/config.php';
require_once EMAIL_MOD . '/Email.php';
require_once ENUMS_PATH . '/User_Type.php';
require_once USER_MOD . '/Account_User.php';
require_once USER_MOD . '/Normal_User.php';
require_once APPT_MOD . '/Appointment_Record.php';

class EmailTemplate {

    private const LINEBREAK = "<br/><br/>";

    //============================================
    //      Basic Email Templates Generated By The System
    //============================================
    public static function template_passwordreset(string $to, string $token): void {

        // -- Check User Type &  Set Recipient
        $recipient_usertype = Account_User::retrieve_user_type($to);

        if ($recipient_usertype == User_Type::PATIENT || $recipient_usertype == User_Type::MEDICAL_PERSONNEL):
            $to_name = Normal_User::retrieve_user_fullname($to);

        elseif ($recipient_usertype == User_Type::FACIILITY_ADMIN || $recipient_usertype == User_Type::SUPER_ADMIN):
            $to_name = Admin::retrieve_admin_name($to);
        endif;

        // -- Email Subject
        $subject = "FYP-21-S2-24: Password Reset";

        # -- Token Expiry Date Needs To Be Set -- #
        // -- Password Reset Link With Token (To Be Added To The Email Message)
        // <link>?token=<passwordtoken>&email=<email>
        $unique_password_url = "https://myappointment.tracieqwynn.tech/forgotpassword/reset.php?token={$token}&email={$to}";
        $request_another_url = "https://myappointment.tracieqwynn.tech/forgotpassword/";


        // -- Clickable Links
        $user_email = "<a href=mailto:{$to}>{$to}</a>";
        $reset_password = "<a href={$unique_password_url} style='color:red; text-decoration:none;'>here</a>";
        $reset_password_url = "<a href={$unique_password_url}>{$unique_password_url}</a>";
        $request_another = "<a href={$request_another_url} style='color:teal;'>request another</a>";

        // -- Miscellaneous
        $sign_off = "Sincerely, <br/>FYP-21-S2-24 Team";

        // -- Message
        $message = "<span style='color:black;'>Hi {$to_name}," . self::LINEBREAK;
        $message .= "We have received a request to reset the password for the MyAppointment account associated with {$user_email}. " . self::LINEBREAK;
        $message .= "You can reset your password by clicking {$reset_password} or copy the link below in your browser:<br/>";
        $message .= "{$reset_password_url}" . self::LINEBREAK . self::set_mailbutton("Change Password", $unique_password_url) . self::LINEBREAK;
        $message .= "If you did make this request, please disregard this email. ";
        $message .= "Please note that your password will not change unless you click the link above and create a new one. ";
        $message .= "This link will expire in one day. If your link has expired, you can always {$request_another}. " . self::LINEBREAK;
        $message .= "If you have requested multiple reset emails, please make sure you click the link inside the most recent email." . self::LINEBREAK;
        $message .= "{$sign_off}</span>";

        Email::sendEmail($to, $subject, $message);
    }

    // -- When User Successfully Change Their Password -- //
    public static function template_passwordchanged(string $to) {

        // -- Check User Type &  Set Recipient
        $recipient_usertype = Account_User::retrieve_user_type($to);

        if ($recipient_usertype == User_Type::PATIENT || $recipient_usertype == User_Type::MEDICAL_PERSONNEL):
            $to_name = Normal_User::retrieve_user_fullname($to);

        elseif ($recipient_usertype == User_Type::FACIILITY_ADMIN || $recipient_usertype == User_Type::SUPER_ADMIN):
            $to_name = Admin::retrieve_admin_name($to);
        else:
            $to_name = "";
        endif;
        // -- Email Subject
        $subject = "FYP-21-S2-24: Password has been changed";

        // -- Miscellaneous
        $sign_off = "Sincerely, <br/>FYP-21-S2-24 Team";
        $timestamp = new Time();
        $date = Time::date_format_change($timestamp->get_date());
        $time_12hour = Time::to_12hours($timestamp->get_time(), false);

        // -- Message
        $message = "<span style='color:black;'>Hi {$to_name}," . self::LINEBREAK;
        $message .= "Your password was recently changed on {$date} at {$time_12hour} (Singapore Standard Time)." . self::LINEBREAK;
        $message .= "If you are aware of this change, please disregard this email. " . self::LINEBREAK;
        $message .= "If it wasn't you who changed it, please reply to this email as someone else may have access to your account. " . self::LINEBREAK;
        $message .= "{$sign_off}</span>";

        Email::sendEmail($to, $subject, $message);
    }

    // -- OTP IS SENT TO THE USER EMAIL TO VERIFY THE LEGITIMACY OF THE EMAIL
    public static function template_emailotp(string $to, string $otp) {
        // -- Email Subject
        $subject = "FYP-21-S2-24: Email OTP Request";

        // -- Miscellaneous
        $sign_off = "Sincerely, <br/>FYP-21-S2-24 Team";
        $timestamp = new Time();
        $date = Time::date_format_change($timestamp->get_date());
        $time_12hour = Time::to_12hours($timestamp->get_time(), false);

        // -- Message
        $message = "<span style='color:black;'>Dear Value User, " . self::LINEBREAK;
        $message .= "You have requested for a One-time Pin from MyAppointment on {$date} at {$time_12hour} (Singapore Standard Time)." . self::LINEBREAK;
        $message .= "Your OTP is: <b>{$otp}</b>" . self::LINEBREAK;
        $message .= "If you are aware of this change, please disregard this email. " . self::LINEBREAK;
        $message .= "If it wasn't you who changed it, please reply to this email as someone else may have access to your account. " . self::LINEBREAK;
        $message .= "{$sign_off}</span>";

        Email::sendEmail($to, $subject, $message);
    }

    public static function template_emailchanged(string $to, string $new_email): void {

        // -- Check User Type &  Set Recipient
        $recipient_usertype = Account_User::retrieve_user_type($new_email);

        if ($recipient_usertype == User_Type::PATIENT || $recipient_usertype == User_Type::MEDICAL_PERSONNEL):
            $to_name = Normal_User::retrieve_user_fullname($new_email);

        elseif ($recipient_usertype == User_Type::FACIILITY_ADMIN || $recipient_usertype == User_Type::SUPER_ADMIN):
            $to_name = Admin::retrieve_admin_name($new_email);
        else:
            $to_name = "";
        endif;

        // -- Email Subject
        $subject = "FYP-21-S2-24: Email Change";

        // -- Miscellaneous
        $sign_off = "Sincerely, <br/>FYP-21-S2-24 Team";
        $timestamp = new Time();
        $date = Time::date_format_change($timestamp->get_date());
        $time_12hour = Time::to_12hours($timestamp->get_time(), false);

        // -- Message
        $message = "<span style='color:black;'>Hi {$to_name}," . self::LINEBREAK;
        $message .= "Your <b>email</b> was recently changed from {$to} to {$new_email} on {$date} at {$time_12hour} (Singapore Standard Time)." . self::LINEBREAK;
        $message .= "If you are aware of this change, please disregard this email. " . self::LINEBREAK;
        $message .= "If it wasn't you who changed it, please reply to this email as someone else may have access to your account. " . self::LINEBREAK;
        $message .= "{$sign_off}</span>";

        Email::sendEmail($to, $subject, $message);
    }

    public static function template_basicinfochanged(string $to): void {

        // -- Check User Type &  Set Recipient
        $recipient_usertype = Account_User::retrieve_user_type($to);

        if ($recipient_usertype == User_Type::PATIENT || $recipient_usertype == User_Type::MEDICAL_PERSONNEL):
            $to_name = Normal_User::retrieve_user_fullname($to);

        elseif ($recipient_usertype == User_Type::FACIILITY_ADMIN || $recipient_usertype == User_Type::SUPER_ADMIN):
            $to_name = Admin::retrieve_admin_name($to);
        else:
            $to_name = "";
        endif;

        // -- Email Subject
        $subject = "FYP-21-S2-24: Basic Profile Information Change";

        // -- Miscellaneous
        $sign_off = "Sincerely, <br/>FYP-21-S2-24 Team";
        $timestamp = new Time();
        $date = Time::date_format_change($timestamp->get_date());
        $time_12hour = Time::to_12hours($timestamp->get_time(), false);

        // -- Message
        $message = "<span style='color:black;'>Hi {$to_name}," . self::LINEBREAK;
        $message .= "Your contact and/or address was recently updated on {$date} at {$time_12hour} (Singapore Standard Time)." . self::LINEBREAK;
        $message .= "If you are aware of this change, please disregard this email. " . self::LINEBREAK;
        $message .= "If it wasn't you who changed it, please reply to this email as someone else may have access to your account. " . self::LINEBREAK;
        $message .= "{$sign_off}</span>";

        Email::sendEmail($to, $subject, $message);
    }

    // -- Verification Email Sent To User -- //
    public static function template_patientregistration(string $to) {

        // -- Check User Type &  Set Recipient
        $recipient_usertype = Account_User::retrieve_user_type($to);

        if ($recipient_usertype == User_Type::PATIENT || $recipient_usertype == User_Type::MEDICAL_PERSONNEL):
            $to_name = Normal_User::retrieve_user_fullname($to);

        elseif ($recipient_usertype == User_Type::FACIILITY_ADMIN || $recipient_usertype == User_Type::SUPER_ADMIN):
            $to_name = Admin::retrieve_admin_name($to);
        else:
            $to_name = "";
        endif;

        // -- Email Subject
        $subject = "FYP-21-S2-24: Registration";

        // -- Miscellaneous
        $sign_off = "Sincerely, <br/>FYP-21-S2-24 Team";

        // -- Message
        $message = "<span style='color:black;'>Hi {$to_name}, " . self::LINEBREAK;
        $message .= "Thank you for registering with FYP-21-S2-24's MyAppointment. " . self::LINEBREAK;
        $message .= "{$sign_off}</span>";

        Email::sendEmail($to, $subject, $message);
    }

    // -- Sent When User Book An Appointment (Show Appointment Schedule) -- //
    public static function template_bookappointment(string $to, Appointment_Record $appt_info) {

        // -- Email Subject
        $subject = "FYP-21-S2-24: New Appointment";

        // -- Check User Type &  Set Recipient
        $recipient_usertype = Account_User::retrieve_user_type($to);
        if ($recipient_usertype == User_Type::PATIENT || $recipient_usertype == User_Type::MEDICAL_PERSONNEL):
            $to_name = Normal_User::retrieve_user_fullname($to);
        else:
            $to_name = "";
        endif;


        // -- Miscellaneous
        $sign_off = "Sincerely, <br/>FYP-21-S2-24 Team";

        // -- Message
        $message = "<span style='color:black;'>Hi {$to_name}, " . self::LINEBREAK;
        $message .= "Your <b>{$appt_info->get_appointmenttype()}</b> appointment booking at {$appt_info->get_facility()->get_facilityname()} has been confirmed!" . self::LINEBREAK;
        $message .= "<b>Appointment Details</b>" . self::LINEBREAK;
        $message .= "Date: {$appt_info->get_appointmentslot()->get_slot_description()}" . self::LINEBREAK;
        $message .= "Location: {$appt_info->get_facility()->get_address()} " . self::LINEBREAK;
        $message .= "{$sign_off}</span>";

        Email::sendEmail($to, $subject, $message);
    }

    // -- Sent When User Book An Appointment (Show Appointment Schedule) -- //
    public static function template_cancelappointment(string $to, Appointment_Record $appt_info) {

        // -- Email Subject
        $subject = "FYP-21-S2-24: Cancelled Appointment";

        // -- Check User Type &  Set Recipient
        $recipient_usertype = Account_User::retrieve_user_type($to);
        if ($recipient_usertype == User_Type::PATIENT || $recipient_usertype == User_Type::MEDICAL_PERSONNEL):
            $to_name = Normal_User::retrieve_user_fullname($to);
        else:
            $to_name = "";
        endif;


        // -- Miscellaneous
        $sign_off = "Sincerely, <br/>FYP-21-S2-24 Team";

        // -- Message
        $message = "<span style='color:black;'>Hi {$to_name}, " . self::LINEBREAK;
        $message .= "Your have CANCELLED your <b>{$appt_info->get_appointmenttype()}</b> appointment at {$appt_info->get_facility()->get_facilityname()}!" . self::LINEBREAK;
        $message .= "<b>Appointment Details</b>" . self::LINEBREAK;
        $message .= "Date: {$appt_info->get_appointmentslot()->get_slot_description()}" . self::LINEBREAK;
        $message .= "Location: {$appt_info->get_facility()->get_address()} " . self::LINEBREAK;
        $message .= "{$sign_off}</span>";

        Email::sendEmail($to, $subject, $message);
    }

    // -- Sent When User Reschedule Their Appointment -- //
    public static function template_rescheduleappointment() {
        
    }

    // -- Create Button For Email: VML Used For MSO -- //
    public static function set_mailbutton(string $button_name, string $url) {

        $button = '<div>
            <!--[if mso]>
            <v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="' . $url . '" style="height:60px;v-text-anchor:middle;width:300px;" arcsize="10%" stroke="f" fillcolor="#d62828">
              <w:anchorlock/>
              <center style="color:#ffffff;font-family:sans-serif;font-size:16px;font-weight:bold;">
                ' . $button_name . '
              </center>
            </v:roundrect>
            <![endif]-->
            <![if!mso]>
            <table cellspacing = "0" cellpadding = "0"> <tr>
            <td align = "center" bgcolor = "#d62828" style = "padding: 8px 12px; text-decoration:none !important; -webkit-border-radius: 5px; -moz-border-radius: 5px; border-radius: 5px; color: #ffffff; display: block;">
                <a href = "' . $url . '" style = "font-size:16px; font-weight: bold; font-family:sans-serif; text-decoration:none !important; line-height:40px; width:100%; display:inline-block">
                    <span style = "color:#ffffff ; text-decoration:none !important;">' . $button_name . ' </span>
                </a>
            </td>
            </tr> </table>
        <![endif]>
        </div>';
        return $button;
    }

//                <![if!mso]>#ffffff
//            <![endif]>

    /*           <span style = "color:black ; text-decoration:none !important;">' .  . '
      </span>
     * */
}
