<?php

/*
 *  Email Class: For System Generated Mail Messages
 *      - Mail Message Functions Can Be Customised
 * 
 */

// -- Import PHPMailer Class -- //
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;

// -- Import Other Util Classes -- //
require_once "Time.php";

class Email extends PHPMailer {

    private const SYSMAIL = "fyp.21.s2.24@gmail.com";
    private const APP_PASSWORD = "rzylfksaoemejptd";

    // -- Construct -- //
    public function __construct($exceptions = null) {
        parent::__construct($exceptions);
        $this->isSMTP();
        $this->Host = 'smtp.gmail.com';
        $this->SMTPAuth = true;
        $this->Username = self::SYSMAIL;
        $this->Password = self::APP_PASSWORD; /* @fyp-21-s2-24's App Password */
        $this->SMTPSecure = 'tls';
        $this->Port = 587;

        // -- Default Receipient Settings -- //
        $this->From = self::SYSMAIL;
        $this->FromName = "MyAppointment FYP-21-S2-24";
    }

    // -- Override Parent send() -- //
    public function send() {
        // echo 'Echo From Subclass';
        return parent::send();
    }

    private static function sendEmail(string $to, string $subject, string $message): void {
        // -- Create New Email Object
        $mail = new Email();
        $mail->addAddress($to);

        // -- Content
        $mail->isHTML(true);
        $mail->Subject = $subject;
        $mail->Body = $message;
        $mail->AltBody = $message;
        $mail->send();
    }

    //============================================
    //      Basic Email Templates Generated By The System
    //============================================
    public static function template_passwordreset(string $to, string $token): void {
        // -- Recipient
        $to_name = Account_User::retrieve_user_fullname($to);

        // -- Email Subject
        $subject = "FYP-21-S2-24: Password Reset";


        # -- Token Expiry Date Needs To Be Set -- #
        // -- Password Reset Link With Token (To Be Added To The Email Message)
        // <link>?token=<passwordtoken>&email=<email>
        $unique_password_url = "http://localhost/MyAppointment/public/debugpasswordreset.php?token={$token}&email={$to}";
        $request_another_url = "http://localhost/MyAppointment/public/debugemail-reset.php";


        // -- Clickable Links
        $user_email = "<a href=mailto:{$to}>{$to}</a>";
        $reset_password = "<a href={$unique_password_url} style='color:red; text-decoration:none;'>here</a>";
        $reset_password_url = "<a href={$unique_password_url}>{$unique_password_url}</a>";
        $request_another = "<a href={$request_another_url} style='color:teal;'>request another</a>";

        // -- Miscellaneous
        $break = "<br/><br/>";
        $sign_off = "Sincerely, <br/>FYP-21-S2-24 Team";

        // -- Message
        $message = "<span style='color:black;'>Hi {$to_name},{$break}";
        $message .= "We have received a request to reset the password for the MyAppointment account associated with {$user_email}. {$break}";
        $message .= "You can reset your password by clicking {$reset_password} or copy the link below in your browser:<br/>";
        $message .= "{$reset_password_url}{$break}" . self::set_mailbutton("Change Password", $unique_password_url) . "{$break}";
        $message .= "If you did make this request, please disregard this email. ";
        $message .= "Please note that your password will not change unless you click the link above and create a new one. ";
        $message .= "This link will expire in one day. If your link has expired, you can always {$request_another}. {$break}";
        $message .= "If you have requested multiple reset emails, please make sure you click the link inside the most recent email.{$break}";
        $message .= "{$sign_off}</span>";

        self::sendEmail($to, $subject, $message);
    }

    public static function template_passwordchanged(string $to) {
        // -- Recipient
        $to_name = Account_User::retrieve_user_fullname($to);

        // -- Email Subject
        $subject = "FYP-21-S2-24: Password has been changed";

        // -- Miscellaneous
        $break = "<br/><br/>";
        $sign_off = "Sincerely, <br/>FYP-21-S2-24 Team";
        $timestamp = new Time();
        $date = Time::date_format_change($timestamp->get_date());
        $time_12hour = Time::to_12hours($timestamp->get_time(), false);

        // -- Message
        $message = "<span style='color:black;'>Hi {$to_name}, {$break}";
        $message .= "Your password was recently changed on {$date} at {$time_12hour} (Singapore Standard Time).{$break}";
        $message .= "If you are aware of this change, please disregard this email. {$break}";
        $message .= "If it wasn't you who changed it, please reply to this email as someone else may have access to your account. {$break}";
        $message .= "{$sign_off}</span>";

        self::sendEmail($to, $subject, $message);
    }

    public static function template_registerverifyemail(string $to) {
        // -- Recipient
        $to_name = Account_User::retrieve_user_fullname($to);

        // -- Email Subject
        $subject = "FYP-21-S2-24: Verify Email Address";

        // -- Clickable Links
        $user_email = "<a href=mailto:{$to}>{$to}</a>";

        // -- Miscellaneous
        $break = "<br/><br/>";
        $sign_off = "Sincerely, <br/>FYP-21-S2-24 Team";
        $timestamp = new Time();
        $date = Time::date_format_change($timestamp->get_date());
        $time_12hour = Time::to_12hours($timestamp->get_time(), false);

        // -- Message
        $message = "<span style='color:black;'>Hi {$to_name}, {$break}";
        $message .= "MyAppointment needs to verify your email address before you can start making any appointment.{$break}";
        $message .= "Please verify your email address {$user_email} {$break}";
        $message .= "{$sign_off}</span>";

        self::sendEmail($to, $subject, $message);
    }

    public static function set_mailbutton(string $button_name, string $url) {
        $button = '<div>
            <!--[if mso]>
            <v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="' . $url . '" style="height:40px;v-text-anchor:middle;width:300px;" arcsize="10%" stroke="f" fillcolor="#d62828">
              <w:anchorlock/>
              <center style="color:#ffffff;font-family:sans-serif;font-size:16px;font-weight:bold;padding: 8px 12px;">
                ' . $button_name . '
              </center>
            </v:roundrect>
            <![endif]-->
            <![if!mso]>
            <table cellspacing = "0" cellpadding = "0"> <tr>
            <td align = "center" bgcolor = "#d62828" style = "padding: 8px 12px; text-decoration:none !important; -webkit-border-radius: 5px; -moz-border-radius: 5px; border-radius: 5px; color: #ffffff; display: block;">
                <a href = "' . $url . '" style = "font-size:16px; font-weight: bold; font-family:sans-serif; text-decoration:none !important; line-height:40px; width:100%; display:inline-block">
                    <span style = "color:#ffffff ; text-decoration:none !important;">' . $button_name . ' </span>
                </a>
            </td>
            </tr> </table>
        <![endif]>
        </div>';
        return $button;
    }

//                <![if!mso]>#ffffff
//            <![endif]>

    /*           <span style = "color:black ; text-decoration:none !important;">' .  . '
      </span>
     * */
}
?>

